config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  
  

  
 
  
  resources :articles do
  resources :comments
  end 
 
 
  
  
  
  
   
  

  
end

app/models/article.rb
class Article < ActiveRecord::Base
	# This is an Article Model ---------------------------------------------
	
	# Models in Rails use a singular name, and their corresponding database tables use a plural name. 
	# Rails provides a generator for creating models, which most Rails developers tend to use when creating new models.
	# To create the new model, run this command in your terminal:
	
	# $ bin/rails generate model Article title:string text:text
	
	# With that command we told Rails that we want a Article model, together with a title attribute of type string, and a text attribute of type text. 
	# Those attributes are automatically added to the articles table in the database and mapped to the Article model.
	
	# Active Record is smart enough to automatically map column names to model attributes, 
	# which means you don't have to declare attributes inside Rails models, as that will be done automatically by Active Record.
	# We have just created this file + a  database migration file inside the db/migrate directory.
	
	
	
	# There isn't much to this file - but note that the Article class inherits from ActiveRecord::Base. 
	# Active Record supplies a great deal of functionality to your Rails models for free, including basic database CRUD (Create, Read, Update, Destroy) operations, 
	# data validation, as well as sophisticated search support and the ability to relate multiple models to one another.
    # Rails includes methods to help you validate the data that you send to models. Open the app/models/article.rb file 
	
	        has_many :comments, dependent: :destroy
			validates :title, presence: true,
                    length: { minimum: 5 }
	
	 
	 # These changes will ensure that all articles have a title that is at least five characters long. Rails can validate a variety of conditions in a model, 
	 # including the presence or uniqueness of columns, their format, and the existence of associated objects.
	 
	 # With the validation now in place, when you call @article.save on an invalid article, it will return false. 
	 # If you open app/controllers/articles_controller.rb again, you'll notice that we don't check the result of calling @article.save inside the create action.
	 
	 # If you delete an article, its associated comments will also need to be deleted, otherwise they would simply occupy space in the database. Rails allows you to use the dependent option of an association to achieve this. Modify the Article model, app/models/article.rb, as follows:

							#class Article < ActiveRecord::Base
								#  has_many :comments, dependent: :destroy
								# validates :title, presence: true,
											# length: { minimum: 5 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	# A frequent practice is to place the standard CRUD actions in each CONTROLLER in the following order: 
	# index, show, new, edit, create, update and destroy. 
	
    http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
	
	# block access to the various actions if the person is not authenticated. 
	# Here we use the Rails http_basic_authenticate_with method, which allows access to the requested action if that method allows it.
	
	
	
	
	#-----------------INTRODUCTION -----------------------------------
	# A controller is simply a class that is defined to inherit from ApplicationController. 
	# It's inside this class that you'll define methods that will become the actions for this controller. 
	# These actions will perform CRUD operations on the articles within our system.
	# There are public, private and protected methods in Ruby,
    # but only public methods can be actions for controllers.
	
	#----------------------STEP 4 ------------------------------------
	# Add the corresponding index action for that route inside the ArticlesController in the app/controllers/articles_controller.rb file. 
	# When we write an index action, the usual practice is to place it as the first method in the controller. Let's do it:
	def index
    @articles = Article.all
	end
	
	#---------------------STEP 3 -------------------------------------------------------------------
	# show action is here:
		def show
			@article = Article.find(params[:id])
			
			
		end
		
	# Make sure the above keyword_end are aligned as above or you will run into a syntax error.
	


 	# --------------------STEP 1 -------------------------------------
	# There are public, private and protected methods in Ruby,
    # but only public methods can be actions for controllers so that the controller now looks like this:
	def new
		 @article = Article.new
	end
	# snippet for brevity
	
	
	#----------------------STEP 4--------------------------------------
	# Now let's focus on the "U" part, updating articles. The first step we'll take is adding an edit action to the ArticlesController, 
	# generally between the new and create actions. Subsequently, create an edit.html.erb
	
	def edit
         @article = Article.find(params[:id])
    end
	
	
	#----------------------STEP 2--------------------------------------
	# Define a create action within the ArticlesController class-
	# in app/controllers/articles_controller.rb, underneath the new action
	# What the create action should be doing is saving our new article to the database.
	# When a form is submitted, the fields of the form are sent to Rails as parameters. 
	# These parameters can then be referenced inside the controller actions, typically to perform a particular task.
	# The render method here is taking a very simple hash with a key of plain and value of params[:article].inspect. 
	# The params method is the object which represents the parameters (or fields) coming in from the form. 
	# The params method returns an ActiveSupport::HashWithIndifferentAccess object, which allows you to access the keys of the hash using either strings or symbols. 
	# In this situation, the only parameters that matter are the ones from the form.
	
	
	def create
		@article = Article.new(article_params)
 
		if @article.save
			redirect_to @article
		else
			render 'new'
		
		end
        end	
	# The new action is now creating a new instance variable called @article, and you'll see why that is in just a few moments.
	# Notice that inside the create action we use render instead of redirect_to when save returns false. 
	# The render method is used so that the @article object is passed back to the new template when it is rendered. 
	# This rendering is done within the same request as the form submission.
	
	
	
	#---------------------STEP 5 -------------------------------------------------------------------
	#
	def update
		@article = Article.find(params[:id])
 
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
	end
	end
	# The new method, update, is used when you want to update a record that already exists, and it accepts a hash containing the attributes 
	# that you want to update. As before, if there was an error updating the article we want to show the form back to the user.
	# You don't need to pass all attributes to update. For example, if you'd call @article.update(title: 'A new title') 
	# Rails would only update the title attribute, leaving all other attributes untouched.
	
  
	
	
	#-----------------------------------STEP 6--------------------------------------------------
	# We use the delete method for destroying resources, and this route is mapped to the destroy action inside app/controllers/articles_controller.rb, 
	# which doesn't exist yet. The destroy method is generally the last CRUD action in the controller, and like the other public CRUD actions, 
	# it must be placed before any private or protected methods.
	    def destroy
               @article = Article.find(params[:id])
               @article.destroy
 
                   redirect_to articles_path
         end
	
	# You can call destroy on Active Record objects when you want to delete them from the database. 
	# Note that we don't need to add a view for this action since we're redirecting to the index action.
	 
	
	#---------------------------------VERY IMPORTANT --------------------------------------------
	
	 # Ensure you have a firm grasp of the params method, as you'll use it fairly regularly. 
	 # Let's consider an example URL: http://www.example.com/?username=dhh&email=dhh@email.com. 
	 # In this URL, params[:username] would equal "dhh" and params[:email] would equal "dhh@email.com".
	 # You have to put the edit and update methods above private. 
	 # Anything below private will be a private method and edit and update should be public methods.
 
	private
		def article_params
		params.require(:article).permit(:title, :text)
		end	
	 
	
	 
	 # Here's what's going on: every Rails model can be initialized with its respective attributes, which are automatically mapped to the respective database columns. 
	 # In the first line we do just that (remember that params[:article] contains the attributes we're interested in).
	 # Then, @article.save is responsible for saving the model in the database.  
	 # Next:  We have to whitelist our controller parameters to prevent wrongful mass assignment. 
	 # In this case, we want to both allow and require the title and text parameters for valid use of create. 
	 # The syntax for this introduces require and permit. The change will involve one line in the create action:

       #  @article = Article.new(params.require(:article).permit(:title, :text))
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

<%if false %>
The reason we can use this shorter, simpler form_for declaration to stand in for either 
of the other forms is that @article is a resource corresponding to a full set of RESTful routes, 
and Rails is able to infer which URI and method to use.
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

<% if false %>
Now, let's update the app/views/articles/edit.html.erb view to use this new partial, rewriting it completely.
<% end %>

app/views/articles/edit2.html.erb
<h1>Editing article</h1>
 
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

<% if false %>
The method: :patch option tells Rails that we want this form to be 
submitted via the PATCH HTTP method which is the HTTP method you're expected to 
use to update resources according to the REST protocol.
The first parameter of form_for can be an object, say, @article which would cause
the helper to fill in the form with the fields of the object. Passing in a symbol (:article) 
with the same name as the instance variable (@article) also automagically leads to the same behavior.
<%end%>

app/views/articles/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>
<%= link_to 'New article', new_article_path %>
<h1>Listing articles</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
	  <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= form_for :article, url: articles_path do |f| %>
  ...
<% end %>
 
<%= link_to 'Back', articles_path %>

<% if false %>
The :method and :'data-confirm' options are used as HTML5 attributes so that when the link is clicked, 
Rails will first show a confirm dialog to the user, and then submit the link with method delete. 
This is done via the JavaScript file jquery_ujs which is automatically included into your application's layout 
(app/views/layouts/application.html.erb) when you generated the application. 
Without this file, the confirmation dialog box wouldn't appear.
In general, Rails encourages using resources objects instead of declaring routes manually!!!!!!!!!!!!!!!! 
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

<% if false %>
Now, let's update the app/views/articles/new.html.erb view to use this new partial, rewriting it completely.
<% end %>

app/views/articles/new2.html.erb
<h1>New Article</h1>

<% if false %>
STEP 1: To create a form within this template, you will use a form builder. 
The primary form builder for Rails is provided by a helper method called form_for.
This creates a completely simple form!!!!!!!
<% end %>

<%= form_for :article, url: articles_path do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
 <% if false %>
 ABOVE: We check if there are any errors with @article.errors.any?, 
 and in that case we show a list of all errors with @article.errors.full_messages.
 pluralize is a rails helper that takes a number and a string as its arguments. 
 If the number is greater than one, the string will be automatically pluralized.
 Rails automatically wraps fields that contain an error with a div with class field_with_errors. 
 You can define a css rule to make them standout.
 <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>